Price luggage and ridedetailmodal
Tomas-ody/CarShare_Angular pull request #48
Opened 2024-05-15 06:54 UTC by lukaschymcak

2024-05-18 19:32 UTC, ladislav37 requested changes

2024-05-18 19:32 UTC, ladislav37 commented on carshare-ui/src/app/components/common/ride-card/ride-card.component.html
> +            <span>Ulica 2</span>
Prosim odstran harkodnute texty, bude uplne stacit ked tam bude mesto..

2024-05-18 19:32 UTC, ladislav37 commented on carshare-ui/src/app/components/common/ride-card/ride-card.component.html
> +              <span>{{ timeParser(ride.rideDateTime) }}</span>
Treba pridat medzeru medzi datum a cas...

2024-05-18 19:36 UTC, ladislav37 requested changes

2024-05-18 19:36 UTC, ladislav37 commented on carshare-ui/src/assets/i18n/sk-SK.json
> +    "luggage": "Miesto pre Batožina",
=> Miesto pre Batožinu

2024-05-20 08:08 UTC, ladislav37 requested changes

2024-05-20 08:08 UTC, ladislav37 commented on carshare-ui/src/app/components/common/ride-card/ride-card.component.html
> +          <h4>Start</h4>
Kazdy text musi byt prelozeny... Teda aj ten End, Date & Time a Details co su dole...

2024-05-20 08:08 UTC, ladislav37 commented on carshare-ui/src/app/components/common/ride-card/ride-card.component.html
> +      <h2>Driver details</h2>
A dalsie neprelozene texty...

2024-05-20 09:15 UTC, lukaschymcak commented on carshare-ui/src/app/components/common/ride-card/ride-card.component.html
> +      <h2>Driver details</h2>
furt zabudnem na preklad :D

2024-05-20 10:05 UTC, merged